### ISSUE TITLE
Remove offchain cells when applied transaction committed

### ISSUE THREAD

**Issue by TheWaWaR** [nervosnetwork/ckb-sdk-rust#40]
Currently a `CellCollector` can only call `reset()` to clear offchain cells, this may not what user want. Users may want only remove the transaction committed to main chain, so they can use the `CellCollector` for long time.

**Comment by sopium** [comment]
I can try this.

**Comment by liuck8080** [comment]
https://github.com/nervosnetwork/ckb-sdk-rust/pull/50
