### ISSUE TITLE
Improve jsonrpc client implementation

### ISSUE THREAD

**Issue by TheWaWaR** [nervosnetwork/ckb-sdk-rust#46]
* Use `use jsonrpc_derive::rpc;` to declare all rpc methods
* Handle special verbosity with wrapper rpc methods, for example:
  - `get_block` : Get block use json format (call `get_block` with `verbosity=2`)
  - `get_block_bin`: Get block by molecule encoded block data (call `get_block` with `verbosity=0`)

**Comment by sopium** [comment]
Although I wrote my own JSONRPC [proc macros](https://docs.rs/jsonrpc-utils/latest/jsonrpc_utils/attr.rpc_client.html), it doesn't seem necessary to use one in ckb-sdk-rust.

And if I'm reading correctly the special wrapper methods already exist now.

So this issue can be closed?

**Comment by liuck8080** [comment]
Yea, it can be closed
