### ISSUE TITLE
The get_block/get_lock_by_number rpc method does not support passing parameters verbosity/with_cycles

### ISSUE THREAD

**Issue by 15168316096** [nervosnetwork/ckb-sdk-rust#52]
Version:v2.4.0
Script:The get_block/get_lock_by_number rpc method need to support passing parameters verbosity/with_cycles
ScreenShot:
![image](https://user-images.githubusercontent.com/45781590/212631294-e3484029-7009-434e-b704-87694c2be4a5.png)

**Comment by liuck8080** [comment]
The PR https://github.com/nervosnetwork/ckb-sdk-rust/pull/51 handles this problem.

**Comment by liuck8080** [comment]
The PR  already merged
