### ISSUE TITLE
Enforce Semver

### ISSUE THREAD

**Issue by WilfredTA** [nervosnetwork/ckb-sdk-rust#9]
The bump from version 1.0.0 to 1.0.1 created breaking changes by removing `GenesisInfo`. Such a change should be reflected in a version increment of greater significance than patch version update.

**Comment by TheWaWaR** [comment]
> The bump from version 1.0.0 to 1.0.1 created breaking changes by removing `GenesisInfo`. Such a change should be reflected in a version increment of greater significance than patch version update.

Sorry, you are right, must be careful next time.
