### ISSUE TITLE
The rust sdk needs to cover the automated test regression of the example case on ci

### ISSUE THREAD

**Issue by 15168316096** [nervosnetwork/ckb-sdk-rust#95]
Does the example of rust sdk run on ci? This needs to be added. The purpose is to prevent some crates from being upgraded, causing the case to become passively outdated and unable to build normally.

- https://github.com/nervosnetwork/ckb-sdk-rust/blob/master/Makefile#L11
- https://github.com/nervosnetwork/ckb-sdk-rust/tree/master/examples

### **expect add workflows steps**

- cargo build --examples
- cargo run --examples examples_name

**Comment by eval-exec** [comment]
iu小迷弟 ***@***.***> writes:

> Does the example of rust sdk run on ci? This needs to be added. The purpose is to prevent some crates from being
> upgraded, causing the case to become passively outdated and unable to build normally.
>
> * https://github.com/nervosnetwork/ckb-sdk-rust/blob/master/Makefile#L11
> * https://github.com/nervosnetwork/ckb-sdk-rust/tree/master/examples
>
> expect add workflows steps
>
> * cargo build --examples
> * cargo run --examples examples_name
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.


-- 

@eval-exec self assigned.
